AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
SEED: 42
TF_SEED: 768
HEIGHT: 224
WIDTH: 224
CHANNELS: 3
